=== Bazovsky/ha-jdbc/doc/src/content/xdocs/xsd/ha-jdbc-2.0.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="http://ha-jdbc.sourceforge.net" xmlns="http://ha-jdbc.sourceforge.net" elementFormDefault="qualified">
	<xs:element name="ha-jdbc">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="distributable" minOccurs="0">
					<xs:complexType>
						<xs:attribute name="config" type="xs:anyURI" default="stacks.xml"></xs:attribute>
						<xs:attribute name="stack" type="xs:string" default="udp"></xs:attribute>
						<xs:attribute name="timeout" type="xs:nonNegativeInteger" default="1000"></xs:attribute>
					</xs:complexType>
				</xs:element>
				<xs:element name="sync" minOccurs="1" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:group ref="property" minOccurs="0" maxOccurs="unbounded"></xs:group>
						</xs:sequence>
						<xs:attribute name="id" type="xs:ID" id="sync" use="required"></xs:attribute>
						<xs:attribute name="class" type="xs:string" use="required"></xs:attribute>
					</xs:complexType>
				</xs:element>
				<xs:choice minOccurs="1" maxOccurs="unbounded">
					<xs:element name="database-cluster">
						<xs:complexType>
							<xs:sequence>
								<xs:element name="database" minOccurs="1" maxOccurs="unbounded">
									<xs:complexType>
										<xs:sequence>
											<xs:element name="driver" type="xs:string" minOccurs="0"></xs:element>
											<xs:element name="url" type="xs:string"></xs:element>
											<xs:group ref="property" minOccurs="0" maxOccurs="unbounded"></xs:group>
											<xs:group ref="authentication" minOccurs="0"></xs:group>
										</xs:sequence>
										<xs:attributeGroup ref="database"></xs:attributeGroup>
									</xs:complexType>
								</xs:element>
							</xs:sequence>
							<xs:attributeGroup ref="cluster"></xs:attributeGroup>
						</xs:complexType>
					</xs:element>
					<xs:element name="datasource-cluster">
						<xs:complexType>
							<xs:sequence>
								<xs:element name="datasource" minOccurs="1" maxOccurs="unbounded">
									<xs:complexType>
										<xs:sequence>
											<xs:element name="name" type="xs:string"></xs:element>
											<xs:group ref="property" minOccurs="0" maxOccurs="unbounded"></xs:group>
											<xs:group ref="authentication" minOccurs="0"></xs:group>
										</xs:sequence>
										<xs:attributeGroup ref="database"></xs:attributeGroup>
									</xs:complexType>
								</xs:element>
							</xs:sequence>
							<xs:attributeGroup ref="cluster"></xs:attributeGroup>
						</xs:complexType>
					</xs:element>
				</xs:choice>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:group name="property">
		<xs:sequence>
			<xs:element name="property" maxOccurs="unbounded">
				<xs:complexType>
					<xs:simpleContent>
						<xs:extension base="xs:string">
							<xs:attribute name="name" type="xs:string" use="required"></xs:attribute>
						</xs:extension>
					</xs:simpleContent>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:group>
	<xs:group name="authentication">
		<xs:sequence>
			<xs:element name="user" type="xs:string"></xs:element>
			<xs:element name="password" type="xs:string"></xs:element>
		</xs:sequence>
	</xs:group>
	<xs:attributeGroup name="cluster">
		<xs:attribute name="id" type="xs:string" use="required"></xs:attribute>
		<xs:attribute name="balancer" use="required">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:enumeration value="simple"></xs:enumeration>
					<xs:enumeration value="random"></xs:enumeration>
					<xs:enumeration value="round-robin"></xs:enumeration>
					<xs:enumeration value="load"></xs:enumeration>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="default-sync" type="xs:IDREF" use="required"></xs:attribute>
		<xs:attribute name="dialect" type="xs:string" default="standard"></xs:attribute>
		<xs:attribute name="meta-data-cache" use="required">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:enumeration value="none"></xs:enumeration>
					<xs:enumeration value="lazy"></xs:enumeration>
					<xs:enumeration value="eager"></xs:enumeration>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="transactions" use="required">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:enumeration value="local"></xs:enumeration>
					<xs:enumeration value="xa"></xs:enumeration>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="auto-activate-schedule" type="xs:string"></xs:attribute>
		<xs:attribute name="failure-detect-schedule" type="xs:string"></xs:attribute>
		<xs:attribute name="min-threads" type="xs:nonNegativeInteger" default="0"></xs:attribute>
		<xs:attribute name="max-threads" type="xs:positiveInteger" default="100"></xs:attribute>
		<xs:attribute name="max-idle" type="xs:nonNegativeInteger" default="60"></xs:attribute>
		<xs:attribute name="detect-identity-columns" type="xs:boolean" default="true"></xs:attribute>
		<xs:attribute name="detect-sequences" type="xs:boolean" default="true"></xs:attribute>
	</xs:attributeGroup>
	<xs:attributeGroup name="database">
		<xs:attribute name="id" type="xs:string" use="required"></xs:attribute>
		<xs:attribute name="weight" type="xs:nonNegativeInteger" default="1"></xs:attribute>
	</xs:attributeGroup>
</xs:schema>

=== Bazovsky/ha-jdbc/src/test/resources/ha-jdbc.xml
<?xml version="1.0"?>
<!--
	HA-JDBC: High-Availability JDBC
	Copyright 2004-2009 Paul Ferraro
	
	This program is free software: you can redistribute it and/or modify
	it under the terms of the GNU Lesser General Public License as published by
	the Free Software Foundation, either version 3 of the License, or
	(at your option) any later version.
	
	This program is distributed in the hope that it will be useful,
	but WITHOUT ANY WARRANTY; without even the implied warranty of
	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
	GNU Lesser General Public License for more details.

	You should have received a copy of the GNU Lesser General Public License
	along with this program.  If not, see <http://www.gnu.org/licenses/>.
-->
<!--DOCTYPE ha-jdbc SYSTEM "../doc/src/content/xdocs/dtd/ha-jdbc-2.0.dtd"-->
<!--ha-jdbc xmlns="http://ha-jdbc.sourceforge.net" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://ha-jdbc.sourceforge.net ../doc/src/content/xdocs/xsd/ha-jdbc-2.0.xsd"-->
<ha-jdbc>
	<sync id="diff" class="net.sf.hajdbc.sync.DifferentialSynchronizationStrategy">
		<property name="fetchSize">100</property>
		<property name="maxBatchSize">50</property>
	</sync>
	<cluster balancer="simple" default-sync="diff" meta-data-cache="none" transaction-mode="parallel">
		<database id="database1" weight="1">
			<driver>net.sf.hajdbc.sql.MockDriver</driver>
			<url>jdbc:mock:database1</url>
			<property name="ssl">true</property>
			<user>root</user>
			<password>password</password>
		</database>
		<database id="database2" weight="2">
			<driver>net.sf.hajdbc.sql.MockDriver</driver>
			<url>jdbc:mock:database2</url>
			<user>root</user>
		</database>
	</cluster>
</ha-jdbc>
