=== Bazovsky/ha-jdbc/ha-jdbc/doc/src/content/dtd/ha-jdbc-1.0.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!--
	HA-JDBC: High-Availability JDBC
	Copyright (C) 2004 Paul Ferraro

	This library is free software; you can redistribute it and/or modify it 
	under the terms of the GNU Lesser General Public License as published by the 
	Free Software Foundation; either version 2.1 of the License, or (at your 
	option) any later version.
	
	This library is distributed in the hope that it will be useful, but WITHOUT
	ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or 
	FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License 
	for more details.

	You should have received a copy of the GNU Lesser General Public License
	along with this library; if not, write to the Free Software Foundation, 
	Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA

	Contact: ferraro@users.sourceforge.net

	This DTD module is identified by the PUBLIC and SYSTEM identifiers:

	PUBLIC "-//HA-JDBC//DTD HA-JDBC 1.0//EN"
	SYSTEM "http://ha-jdbc.sourceforge.net/dtd/ha-jdbc-1.0.dtd"
-->
<!ELEMENT ha-jdbc (distributable?, cluster+)>

<!ELEMENT distributable EMPTY>
<!ATTLIST distributable
	protocol CDATA #REQUIRED
>
<!ELEMENT cluster (validate-sql?, create-foreign-key-sql?, drop-foreign-key-sql?, create-index-sql?, drop-index-sql?, (database+ | datasource+ | pool-datasource+ | xa-datasource+))>
<!ATTLIST cluster
	name CDATA #REQUIRED
>
<!ELEMENT validate-sql (#PCDATA)>
<!ELEMENT create-foreign-key-sql (#PCDATA)>
<!ELEMENT drop-foreign-key-sql (#PCDATA)>
<!ELEMENT create-index-sql (#PCDATA)>
<!ELEMENT drop-index-sql (#PCDATA)>

<!ENTITY % authentication-info "(user, password)?">

<!ELEMENT database %authentication-info;>
<!ATTLIST database
	url CDATA #REQUIRED
	driver CDATA #REQUIRED
>
<!ELEMENT datasource %authentication-info;>
<!ATTLIST datasource name CDATA #REQUIRED>
<!ELEMENT pool-datasource %authentication-info;>
<!ATTLIST pool-datasource name CDATA #REQUIRED>
<!ELEMENT xa-datasource %authentication-info;>
<!ATTLIST xa-datasource name CDATA #REQUIRED>
<!ELEMENT user (#PCDATA)>
<!ELEMENT password (#PCDATA)>

=== Bazovsky/ha-jdbc/ha-jdbc/doc/src/content/dtd/ha-jdbc.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE ha-jdbc SYSTEM "file:///C:/ha-jdbc/doc/src/content/dtd/ha-jdbc-1.0.dtd">
<ha-jdbc>
	<distributable protocol=""/>
	<cluster name="">
		<validate-sql>SELECT 1</validate-sql>
		<create-foreign-key-sql>ALTER TABLE {1} ADD CONSTRAINT FOREIGN KEY {0} REFERENCES {2} ({3})</create-foreign-key-sql>
		<drop-foreign-key-sql>ALTER TABLE {1} DROP CONSTRAINT {0}</drop-foreign-key-sql>
		<create-index-sql>CREATE INDEX {0} ON {1} ({2})</create-index-sql>
		<drop-index-sql>DROP INDEX {0}</drop-index-sql>
		<database url="" driver="">
			<user></user>
			<password></password>
		</database>
	</cluster>
	<cluster name="">
		<validate-sql></validate-sql>
		<
	</cluster>
	<cluster name="">
		<datasource name=""></datasource>
	</cluster>
</ha-jdbc>
