=== Bazovsky/ha-jdbc/ha-jdbc/conf/ha-jdbc.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT ha-jdbc (cluster+)>
<!ELEMENT cluster ((driver+)|(datasource+)|(pooled-datasource+)|(xa-datasource+))>
<!ATTLIST cluster
	name NMTOKEN #REQUIRED
	validate-sql CDATA #REQUIRED
>
<!--	type (Driver|DataSource|ConnectionPoolDataSource|XADataSource) #REQUIRED-->
<!ELEMENT driver (url,(user,password)?)>
<!ELEMENT datasource (name,(user,password)?)>
<!ELEMENT pooled-datasource (name,(user,password)?)>
<!ELEMENT xa-datasource (name,(user,password)?)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT password (#PCDATA)>
<!ELEMENT url (#PCDATA)>
<!ELEMENT user (#PCDATA)>

=== Bazovsky/ha-jdbc/ha-jdbc/conf/ha-jdbc.xml
<?xml version="1.0"?>
<!DOCTYPE ha-jdbc SYSTEM "ha-jdbc.dtd">
<ha-jdbc>
	<cluster name="resolution" validate-sql="SELECT 1">
		<driver>
			<url>jdbc:postgresql://localhost:5432/resolution</url>
			<user>postgres</user>
			<password>postgres</password>
		</driver>
		<driver>
			<url>jdbc:postgresql://remote:5432/resolution</url>
			<user>postgres</user>
			<password>postgres</password>
		</driver>
	</cluster>
	<cluster name="subsription" validate-sql="SELECT 1">
		<datasource>
			<name>java:comp/env/jdbc/subsription</name>
			<user>postgres</user>
			<password>postgres</password>
		</datasource>
		<datasource>
			<name>java:comp/env/jdbc/subsription</name>
			<user>postgres</user>
			<password>postgres</password>
		</datasource>
	</cluster>
</ha-jdbc>
